### PR TITLE
[Flavour] Restructure and Overhaul for eventual Prod-Grade use.

### PR DESCRIPTION
**Pull request by SpcFORK**
I've restructured the codebase so that it will work with various JS APIs while also fixing up the structure for optimal code.
😎👍

It should now also work with JSDOM (If you were going to serve)!!

- Extra methods,
- Class structure,
- Constructor Mapping.

- Toggle Tags
- Etc...

### CODE REVIEW

**Comment by rexim** [comment]
Why did you replace my framework with React?

**Comment by rexim** [comment]
I have no idea what you are doing in here, but whatever you are doing is outside of the scope of the project, that's for sure.

**Comment by SpcFORK** [comment]
> Why did you replace my framework with React?

It's front-end only, it does not use React.

**Comment by SpcFORK** [comment]
> I have no idea what you are doing in here, but whatever you are doing is outside of the scope of the project, that's for sure.

Yes, I have my own ideas for this simple framework base.
Looked cool, although it was simple before.

Still riding on the premise of being anti-React.
Just the code was "not good enough to use".

I have recently been refactoring into using JS Modules to fix code density.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

**Comment by rexim** [comment]
Looks like you just want to develop your own project. In that case I think you may find this document useful: https://docs.github.com/en/get-started/quickstart/create-a-repo

**Comment by synzr** [comment]
holy shit

**Comment by SpcFORK** [comment]
> holy shit

For real,
Check out https://github.com/SpcFORK/Grecha-Susha.js/tree/master for a non-forked, separate version.

**Pull request closed without merging**
